name: serviceproduction
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^1.0.6
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  # Ensures that the Material Icons font is included.
  uses-material-design: true

  # Add assets to your application.
  assets:
    - asset/images/
    - asset/register/

  # An image asset can refer to one or more resolution-specific "variants":
  # https://flutter.dev/to/resolution-aware-images

  # For details on adding assets from package dependencies:
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application:
  # https://flutter.dev/custom-fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
